### ISSUE TITLE
Mayonnaise on a escalator

### ISSUE THREAD

**Issue by Py10lolz** [NekoIceTeam/NekoIceBot#2]
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye
Mayonnaise on a escalator
It's going upstairs so see u later
Bye bye

**Comment by Sobble2546** [comment]
Nice

**Comment by NekoIceCream** [comment]
Bruh
