### ISSUE TITLE
delete/private this repository :wheeze:

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [NekoIceTeam/NekoIceBot#6]
encrypted code zip :wheeze: :trollface: :amogus: :sus: :pensive: :flushed:

**Comment by Quit75Gaming** [comment]
gws ya bro🗿

I don't know what you mean🤣

**Comment by NekoIceCream** [comment]
> encrypted code zip :wheeze: :trollface: :amogus: :sus: 😔 😳

I will give the code

If i ready 😆

**Comment by RealEthanPlayzDev** [comment]
wheeze ok
